### ISSUE TITLE
Missing logging directory

### ISSUE THREAD

**Issue by sameo** [containers/virtcontainers#11]
We should define a logging directory (`/var/lib/virtcontainers/logs/`)and file and push all our logs there.

**Comment by wcwxyz** [comment]
How about using a logger interface passed down from higher level, like ciao/qemu does. So we can leave logging totally to the application. What do you think?

**Comment by egernst** [comment]
I think this is pretty stale/uneccessary at this point, as we're using the system log.  Closing.  @sameo - please reopen if I am mistaken and this is still useful...
