### ISSUE TITLE
Adapt CC proxy configuration structure

### ISSUE THREAD

**Issue by sameo** [containers/virtcontainers#147]
The CC proxy configuration should only embed a URL, as this is all virtcontainers need to connect to the proxy.

Changing this structure is a multi steps task:

1. On virtcontainers:
- [x] Change `CCProxyConfig` to at least include a URL
- [x] Parse the URL to understand how virtcontainers should connect to the proxy
2. On the runtime implementation"
- [x] Change the proxy configuration section to include a URL
- [x] Parse the configuration file and create a `CCProxyConfig` that includes a URL

**Comment by sboeuf** [comment]
2 points about virtcontainers are covered by: https://github.com/containers/virtcontainers/pull/146

**Comment by sboeuf** [comment]
2 points about runtime implementation are addressed by: https://github.com/clearcontainers/runtime/pull/57

**Comment by sboeuf** [comment]
#146 and clearcontainers/runtime#59 have been merged, we can close this issue.
