### ISSUE TITLE
use exec.Command rather than exec.Cmd

### ISSUE THREAD

**Issue by jodh-intel** [containers/virtcontainers#155]
`runHook()` uses `exec.Cmd{}` directly, but note clearcontainers/runtime/pull/65

**Comment by sboeuf** [comment]
This is not an issue, `exec.Cmd{}` is used on purpose here. We need /usr/bin/dockerd to be reexecuted to be able to call the hook properly. Indeed, `dockerd` does not accept any parameters, but if you re-execute it, it actually does.
