### ISSUE TITLE
TestRemoveNetworkFailureNetworkDoesNotExist is failing on master branch

### ISSUE THREAD

**Issue by jodh-intel** [containers/virtcontainers#166]
Travis had previously passed the code at commit 8362442641ae0a370ba54ebb4d9c22aedd5d240e, but re-running the Travis CI tests now shows it is failing on test `TestRemoveNetworkFailureNetworkDoesNotExist`.

See https://github.com/containers/virtcontainers/pull/165#issuecomment-288696677

**Comment by dlespiau** [comment]
PR #167 seems to have fixed that? Note github supported auto-closing issues based on tags in commit messages: https://help.github.com/articles/closing-issues-via-commit-messages/
