### ISSUE TITLE
Host networking implementation

### ISSUE THREAD

**Issue by sameo** [containers/virtcontainers#2]
# Problem statement

## Networking support from VirtContainers
Enabling host networking for containers usually consists of linking a container network namespace with a host interface. The way this is done is typically done by external plugins complying with the [CNM](https://github.com/docker/libnetwork) or the [CNI](https://github.com/containernetworking/cni) specifications, like e.g. Docker or Kubernetes respectively.

The networking setup is left outside of the runtime specification, so implementing this as part of VirtContainers is somehow a little out of scope. However, in practice the container networking setup and teardown steps are integral parts of the container lifecycle and often dependent on the runtime semantics.

Therefore it seems natural for VirtContainers to at least offer networking setup opt-in. By default, it will not try to do anything related to networking but we want it be able to either call into CNI or CNM plugins if the caller decides to offload that part of the container lifecycle to VirtContainers.

## Plugging namespace networking interfaces with virtual machine ones
The second part of the problem we're trying to solve is caused by the fact that all existing container networking plugins are namespace centric, i.e. they assume that creating an interface (typically one end of a veth pair) within the container networking namespace and linking it back to the host networking plane is enough.

Virtual machines however usually don't see virtual ethernet pairs and only manage to handle TUN/TAP interfaces. Therefore our networking implementation must bridge those virtual machine interfaces with the interface the selected networking plugin created within the container networking namespace.

# Proposal
As an initial step we want to focus on using CNI as our first networking implementation support. The below steps would be integrated into the virtcontainers `CreatePod()` call:

1. Create the pod host networking namespace. Either we create an anonymous namespace or we improve the [ciao qemu](https://github.com/01org/ciao/tree/master/qemu) package so that it optionally starts the qemu process within its own networking namespace.
2. Find the default CNI plugin. The [ocicni](https://github.com/rajatchopra/ocicni) Go package allows us to do that, but we need more flexibility from this API because we need it to return the [CNI plugin result](https://github.com/containernetworking/cni/blob/master/SPEC.md#result) together with the networking interface created by the plugin. Here we should implement a simpler, more flexible API for finding the default CNI plugin, running it, and passing the results upstream.
3. Run the default CNI plugin, fetch the results including the name of the interface created by the plugin.
4. Create the network bridge between the created interface and the VM TAP interface. Here we should allow for multiple interfaces to be set and bridged.
5. Pass the networking setup results to the VM through e.g. cloud-init.

_Document the `StopPod()` path_

**Comment by sameo** [comment]
Adding @mcastelino for review.

**Comment by sboeuf** [comment]
@sameo We have CNI and CNM working pretty well right now. Maybe it would worth to open a new issue in case we have to make some changes to either CNI or CNM, if something changed in their codebase. But for this issue, I think we are done. What do you think ?
