### ISSUE TITLE
hyperstart start() and stop() implementations are not hyperstart specific

### ISSUE THREAD

**Issue by sameo** [containers/virtcontainers#202]
Our only agent implementation, `hyperstart.go`, `start()` and `stop()` implementations are not hyperstart specific. They do pod specific initializations that should be factored into `pod.go`. All agent implementations will have to follow the same steps.

Going one step further, we could argue the `start()` and `stop()` agent interface methods are not needed. I would like to see them removed unless someone has a case for keeping them around. 

In any case, the hyperstart implementation for those 2 methods should be empty.

**Comment by sboeuf** [comment]
Fixed by #205.
