### ISSUE TITLE
Get rid of pause container

### ISSUE THREAD

**Issue by amshinde** [containers/virtcontainers#225]
We introduced a pause container to have a pod running when all containers have finished execution.
Since hyperstart has added support for keeping a pod alive, we should get rid of the pause container and port the changes into clearcontainers repo instead.
In case of docker, we may not want this behaviour altogether, this should be passed as a additional parameter to the agent to indicate if the pod should be kept around.

**Comment by egernst** [comment]
@amshinde - can you update this issue?

**Comment by sboeuf** [comment]
This issue is related to https://github.com/clearcontainers/agent/issues/81.
Indeed, we need to fix the agent first, and then we will be able to adapt virtcontainers.

**Comment by egernst** [comment]
@sboeuf  -- can we update / close?

**Comment by sboeuf** [comment]
Yes, can be closed !
