### ISSUE TITLE
Add support for additional groups while running a container

### ISSUE THREAD

**Issue by amshinde** [containers/virtcontainers#233]
Ref : https://github.com/opencontainers/runtime-spec/blob/master/specs-go/config.go#L89

**Comment by sboeuf** [comment]
We should implement this by changing the Cmd structure from
```go
type Cmd struct {
    ...
    Group string
    ...
}
```
to
```go
type Cmd struct {
    ...
    Groups []string
    ...
}
```

In case our agent support to set only one group, we just need to take `cmd.Groups[0]`.
