### ISSUE TITLE
Add a global debug variable

### ISSUE THREAD

**Issue by sboeuf** [containers/virtcontainers#235]
Let's have a global variable `globalDebug` that would be enabled/disabled through the API `SetLog()`.
When we want to enable the debug, we want it for all components, that's why a global (but not exported) variable would be very convenient.

**Comment by sboeuf** [comment]
@sameo does that makes sense ?

**Comment by egernst** [comment]
@sboeuf -- any updates on this?

**Comment by sboeuf** [comment]
This has been implemented. Can be closed.
