### ISSUE TITLE
Multiple interfaces CNI support

### ISSUE THREAD

**Issue by sameo** [containers/virtcontainers#238]
Our `pkg/cni` package only supports `lo` and a default interface (The first config file found in `/etc/cni/`).

We want to be able to support and configure as many interfaces as we find configuration files.

**Comment by sameo** [comment]
cc @mcastelino

**Comment by egernst** [comment]
A bit different, but we should support network hotplug too, right?

**Comment by mcastelino** [comment]
@sameo @egernst AFAIK our current scan code does not assume a single interface. @sboeuf also unified the CNI and CNM scanning codes. It just assumes a single CNI plugin. So multus which in turn calls multiple CNI plugins will result in multiple interfaces which should get propagated into the VM same as CNM.

**Comment by egernst** [comment]
Yep, agreed @mcastelino   @sameo feel free to re-open if there's a different use case we should consider addressing.
