### ISSUE TITLE
Add gometalinter to virtcontainers

### ISSUE THREAD

**Issue by dlespiau** [containers/virtcontainers#263]
There are quite a few warnings from gometalinter on virtcontainers. Would be nice to address them and start using gometalinter on this project.

**Comment by sboeuf** [comment]
https://github.com/containers/virtcontainers/blob/master/.ci/go-lint.sh
Here is gometalinter. Feel free to tweak it.

**Comment by dlespiau** [comment]
Is is run in CI? I must have missed that part.

**Comment by sboeuf** [comment]
Yes it is used by travis and semaphore when they are calling into make check.

**Comment by dlespiau** [comment]
Never mind then, we can closed this one.
