### ISSUE TITLE
Implement PausePod() and ResumePod()

### ISSUE THREAD

**Issue by jodh-intel** [containers/virtcontainers#267]
`PauseContainer()` and `ResumeContainer()` are required to implement `pause` and `resume` commands in a runtime.

See:

- https://github.com/clearcontainers/runtime/pull/161#issuecomment-303371425
  (also https://github.com/clearcontainers/runtime/issues/99 and https://github.com/clearcontainers/runtime/issues/100).

**Comment by jodh-intel** [comment]
This might need some discussion since currently virtcontainers states are shared between pods and containers. Either we break that design (allowing a new `paused` state for containers only), or we consider also adding `PausePod()` and `ResumePod()`.

@sameo, @sboeuf - what are your thoughts on this?

**Comment by sboeuf** [comment]
I cannot see the use cases right now, but I think it would not hurt to have `PausePod()` and `ResumePod()` as the symmetrical API for `PauseContainer()` and `ResumeContainer()`. And I think we can start basically with the pod ones being a for loop looping over `PauseContainer()` and `ResumeContainer()`.

**Comment by jodh-intel** [comment]
I agree - I can't see an actual need for `PausePod()` / `ResumePod()`, atleast not for an OCI runtime, but maybe other clients will have use-cases.

Yes, we could loop through the containers and call `PauseContainer()`, but there is a better way: use QMP to pause the hypervisor as we currently do for `pause` in https://github.com/01org/clr-oci-runtime.

**Comment by sboeuf** [comment]
Ah yes I can remember we talked about this once. Sounds very good to me.

**Comment by jodh-intel** [comment]
As shown above, I've pushed a WIP branch. It works for both pods and containers, but there is a catch as shown by the `BUG:` comment in `pod.go`.

Imagine this scenario...

- `container1` is in state `running`.
- `container2` is in state `paused`.
- the parent pod is then paused (pod state `paused`, which of course will forcibly pause both `container1` and `container2`).

But what happens when the pod is unpaused? We expect `container1` to be `running` and `container2` to still be `paused` but we cannot represent that without storing the previous container state.

We *could* side-step the problem entirely by requiring the pod status to take precedence over the container state. That would allow, for example, `cc-runtime list` to DTRT and show a container as `paused` even though strictly it is its pod that is `paused` (the container is still `running`). If we go with that approach, we'll have to make an exception to the state-handling code: for pause/resume, a containers state will *not* be updated to reflect that of its pod, but the pods state will be deemed to override the container state.

@sameo, @sboeuf - thoughts?

**Comment by dlespiau** [comment]
Could we only have pause/resume at the pod level instead of containers (or a mix of both)? pausing a pod is a VM operation, pausing a container is a cgroup operation (could be added once we have a better degree of freedom on the agent).

**Comment by sboeuf** [comment]
If we focus on the concept and not how the pause is performed at container/pod level, I would say that the pod status will apply to all containers. This means that whatever the state of container is, if you call into `PausePod()` you will pause every container and update their status to pause, and then pause the VM. When you call into `ResumePod()`, you will resume your VM, call into kill(SIGCONT) for each container, and update the status of every one to Running.
We can maybe skip the pause of every container during the `PausePod()` in case we can send a kill(SIGCONT) to all the containers without any consequences during the resume sequence. Indeed, when we will resume the pod, I assume that resuming the VM will restore all the containers in the same state they were before, meaning that we will end up with some containers running and others resumed. If a running container does gives us an error by receiving SIGCONT if it is already running, then we don't even need to pause all the containers before we pause the VM, we just need to update their statuses.

**Comment by dlespiau** [comment]
I hadn't realized the current solution was using SIGSTOP. It's not great, see https://www.kernel.org/doc/Documentation/cgroup-v1/freezer-subsystem.txt, starting with "Sequences of SIGSTOP and SIGCONT are not always sufficient for stopping
and resuming tasks in userspace."

**Comment by sboeuf** [comment]
Thanks for pointing this @dlespiau. But globally it does not change the logic I think. When you pause a pod, you expect all the containers to be stopped and when you resume it, all the containers are resumed.
That being said, we can pause/resume containers with those cgroups inside hyperstart, but does Docker expect to see the shim process in this state too ?

**Comment by jodh-intel** [comment]
@dlespiau - I 100% agree that we should be using cgroups to control the container processes for `ContainerPause()` / `ContainerResume()`, but this is a first pass implementation using what is currently available to use via hyperstart. If we do want to have separate APIs to pause pods and containers we can always improve the implementation when we add support to the agent.

**Comment by dlespiau** [comment]
Yup, fair enough, SIGSTOP/CONT as a first pass is likely better than nothing.

**Comment by jodh-intel** [comment]
@sameo - any thoughts on this or https://github.com/jodh-intel/virtcontainers/tree/implement-pause+unpause-container ?

**Comment by sameo** [comment]
@jodh-intel sorry for the long delay...

I think as a first step our pause/resume logic should only apply to pods for now, i.e. we should not even export the `Pause/ResumeContainer` API. This would be less confusing and could always be used for the OCI case.
The pod logic would be that all containers will always be in the same `paused/resumed` state, and I think for the QEMU hypervisor we could simply call QMP on the pod VM and declare it paused/resumed, together with all its containers.

Then as a second step we could extend the API to be more granular and allow a per container `pause/resume` operation. IMO the logic behind it should also be kept simple: If a pod has container A in `running` state and container B in `paused` state, then calling `PausePod` will change all containers state to `paused`. That also means this second step will be compatible with the first one.
