### ISSUE TITLE
add --device handling

### ISSUE THREAD

**Issue by egernst** [containers/virtcontainers#309]
today system mounts are bypassed.

In particular /dev should be handled.  For example, you should be able to say:
docker run --device=/dev/vfio/17 and expect it to be mounted within the resulting container.

See: https://github.com/containers/virtcontainers/blob/774316c82940561557a90181e8be70aa802c167e/hyperstart.go#L253

**Comment by egernst** [comment]
@sboeuf  @amshinde @mcastelino

**Comment by sboeuf** [comment]
Yes good point, but I am wondering how we should handle this. Either we get an exception for `/dev/vfio` devices, or we create a very specific list of `/dev` that we want to ignore.

**Comment by egernst** [comment]
We should handle just the devices which are described in the config.json.

Ex: sudo docker run --runtime=runc --device=/dev/vfio -it alpine sh

Now, take a look at the resulting config.json, and you will see a "devices" section:
root@sriov-2:/var/run/docker/libcontainerd/2854615a0f3279652d210842141f7d792166a34289908b227f5d718afb526f61# cat config.json | python -mjson.tool | grep -b10 -a10 vfio
381-    },
388-    "hostname": "2854615a0f32",
420-    "linux": {
435-        "cgroupsPath": "/docker/2854615a0f3279652d210842141f7d792166a34289908b227f5d718afb526f61",
534-        "devices": [
555-            {
569-                "fileMode": 8576,
603-                "gid": 0,
629-                "major": 242,
659-                "minor": 0,
687:                "path": "/dev/vfio/17",
727-                "type": "c",
756-                "uid": 0
781-            }
795-        ],
806-        "maskedPaths": [
831-            "/proc/kcore",
858-            "/proc/latency_stats",
893-            "/proc/timer_list",
925-            "/proc/timer_stats",
958-            "/proc/sched_debug",

**Comment by sboeuf** [comment]
No I get it but I mean that right now we are bypassing some devices described in the config.json because they are handled directly by the agent. No need to take care of those on the host.
In case of `/dev/vfio` we don't want to ignore that, we want to mount it locally so that we can share it through the sharedDir that we give to the agent, right ? Or does `/dev/vfio` have to be passed to qemu ?

**Comment by sboeuf** [comment]
@amshinde Is there any reason why we are so restrictive about ignoring the whole `/dev` directory ?
I think we can easily fix that by using something different than `strings.HasPrefix()`. Indeed, when testing that way, we ignore all the subpaths including /dev.

**Comment by egernst** [comment]
@sboeuf In the case of /dev/vfio, we indeed would see this and then know that we have to pass this device in to the clear container (more specifically, update the qemu cmdline to pass this through).

**Comment by amshinde** [comment]
Currently /dev is mounted within hyperstart which is what we want. Instead of ignoring system mounts we can simply restrict the check to bind mounts. (/dev is not passed as a bind mount).

**Comment by egernst** [comment]
Also -- I *think* these are in a different location within the config.json, compared to the shared host ones...

**Comment by amshinde** [comment]
@sboeuf @egernst getting rid of the check here should be fine and would fix this:
https://github.com/containers/virtcontainers/blob/774316c82940561557a90181e8be70aa802c167e/hyperstart.go#L253

**Comment by amshinde** [comment]
@egernst These are all passed with the "mounts" object in config.json

**Comment by amshinde** [comment]
As last discussed, this is passed as a "devices" attribute in config.json and not as a mount. 
We need to parse "devices", determine the device bdf  and pass the it as a pci passthrough to qemu.
In case where the device needs to be renamed, the agents needs to handle the renaming.

**Comment by mcastelino** [comment]
@sboeuf @egernst @amshinde Today we have a blanket ignore of all the devices passed in. We need to structure the code in a way that we do handle the subset of the devices which we may  be able to handle.

This is also true of the mounts. We assume today that all mounts are shared via 9p. But the mount happens to be a block device, we should provide the option to send it in via virt-io blk. This can be done for example for ceph rbd based volumes. And maybe in the future things like iscsi LUNs.

**Comment by egernst** [comment]
Yes, exactly.  I plan to work on this later this week, unless someone else beats me to it.  If anyone starts looking @ impl, please self-assign.

**Comment by egernst** [comment]
@mcastelino -- correct -- see https://github.com/containers/virtcontainers/issues/308 for mount discussion.

**Comment by egernst** [comment]
already supported...
