### ISSUE TITLE
VM memory size calculation needs deciding

### ISSUE THREAD

**Issue by grahamwhaley** [containers/virtcontainers#337]
Here:
https://github.com/containers/virtcontainers/blob/master/qemu.go#L473
we have the code:
```
memMax := fmt.Sprintf("%dM", int(float64(q.config.DefaultMemSz)*1.5))
	if podConfig.VMConfig.Memory > 0 {
		mem = fmt.Sprintf("%dM", podConfig.VMConfig.Memory)
		intMemMax := int(float64(podConfig.VMConfig.Memory) * 1.5)
```

The `*1.5` multiplier I think may not be correct, and could have been a mis-translation of the original intent of the line:
```
2G,slots=2,maxmem=3G
```
from https://github.com/01org/cc-oci-runtime/blob/master/data/hypervisor.args.in#L11

The intent of the original, having the maxmem 1G larger than the mem, was I believe to leave 1G of space for the nvdimm DAX mapping of the .img file.
Thus, I suspect the code should be more like:
```
const imgExtraMem = 1 * 1024 * 1024
memMax := fmt.Sprintf("%dM", q.config.DefaultMemSz + imgExtraMem))
	if podConfig.VMConfig.Memory > 0 {
		mem = fmt.Sprintf("%dM", podConfig.VMConfig.Memory)
		intMemMax := podConfig.VMConfig.Memory + imgExtraMem )
```

If we agree, let's PR that.

**Comment by wcwxyz** [comment]
@grahamwhaley I've submit a patch https://github.com/containers/virtcontainers/pull/336

**Comment by grahamwhaley** [comment]
Ah, indeed. I didn't put 2&2 together...thx
