### ISSUE TITLE
Rewrite pause binary in go.

### ISSUE THREAD

**Issue by jodh-intel** [containers/virtcontainers#339]
Requiring the pause binary be written in C means we need to build it statically. However, this is problematic on RHEL 7, so let's rewrite it in go for now.

See https://github.com/clearcontainers/packaging/issues/38.

**Comment by wcwxyz** [comment]
As I understand, If you build a static binary written in go, you still need glibc-static. Is that right?

**Comment by gorozco1** [comment]
@wcwxyz No, I don't think so. As long as the source being compiled is native go, the go compiler will statically link the executable. 

Reference: http://blog.hashbangbash.com/2014/04/linking-golang-statically/

**Comment by wcwxyz** [comment]
@gorozco1 Yes, you're right. Thanks for your explanation!
