### ISSUE TITLE
unable to build under virtcontainers

### ISSUE THREAD

**Issue by jodh-intel** [containers/virtcontainers#347]
I just tried to build the package under semaphoreci by copying the platform and build settings from [1].

It appears that `utils/virtcontainers-setup.sh` assumes there is a checkout/`go get` of the official repo in `$GOPATH`. That isn't the case if you try to build `virtcontainers` as a user though. Here's the output of the failed semaphore build for me [2]:

```
var/spool/
var/spool/mail/
var/www/
~/workspace/src/github.com/jodh-intel/virtcontainers
Move to /tmp/tmp.Tnxuf4sq2U/virtcontainers/build
/tmp/tmp.Tnxuf4sq2U/virtcontainers/build ~/workspace/src/github.com/jodh-intel/virtcontainers
Clone cni
Copy CNI config files
Cloning into 'plugins'...cp: cannot stat ‘/home/runner/workspace/src/github.com/containers/virtcontainers/test/cni/10-mynet.conf’: No such file or directory
```

That output corresponds to:

```
cp -r ${busybox_bundle}/* ${pause_bundle}/

echo -e "Move to ${tmpdir}/${virtcontainers_build_dir}"
pushd ${tmpdir}/${virtcontainers_build_dir}
echo "Clone cni"
git clone https://github.com/containernetworking/plugins.git

echo "Copy CNI config files"
cp $GOPATH/src/github.com/containers/virtcontainers/test/cni/10-mynet.conf ${ETCDIR}/cni/net.d/
cp $GOPATH/src/github.com/containers/virtcontainers/test/cni/99-loopback.conf ${ETCDIR}/cni/net.d/
```

Note in the output above that my branch seems to live under `~/workspace/src/github.com/jodh-intel/virtcontainers` and `/home/runner/workspace/src/github.com/containers/virtcontainers/` is ENOENT.

---
[1] - https://semaphoreci.com/clearcontainers/virtcontainers
[2] - https://semaphoreci.com/james-o-hunt/virtcontainers/branches/add-mock-implementation/builds/3

**Comment by egernst** [comment]
is this semaphore specific?

**Comment by sboeuf** [comment]
@egernst no, it's not specific to semaphore, it is about executing the script from a forked branch which does not work.

**Comment by egernst** [comment]
@sboeuf - okay. this doesn't appear to be release gating; let me know if you feel differently.

**Comment by sboeuf** [comment]
Nope, it's not release gating for me either.

**Comment by egernst** [comment]
@jodh-intel -- I assume  you're okay with closing this?  Reopen if you long for semaphoreCI functionality..
