### ISSUE TITLE
CreatePod must rollback actions if fails.

### ISSUE THREAD

**Issue by jcvenegas** [containers/virtcontainers#356]
Today if something goes wrong in `Create Pod` it left VM instances and shims running (and probably registered proxy sessions). 

Related to : https://github.com/clearcontainers/runtime/issues/176

**Comment by egernst** [comment]
Not sure why I can't add gating release label, but this should be.

**Comment by grahamwhaley** [comment]
I see a release gating label on it.... seems to have worked?

**Comment by egernst** [comment]
couldn't type it in, but waffle could do it on my behalf, it seems...

**Comment by egernst** [comment]
@jcvenegas - you may need to join this "group" in order to get assigned.

**Comment by sboeuf** [comment]
Issue also followed here: https://github.com/clearcontainers/runtime/issues/507

**Comment by jcvenegas** [comment]
While delete now try to cleanup more bits from a created container, I would like to test how good it is to remove an incomplete created pod.

**Comment by amyleeland** [comment]
@jcvenegas  should this bug be closed based on PR #360 and https://github.com/clearcontainers/runtime/issues/507 ?

**Comment by jcvenegas** [comment]
yes, we can close it now.
