### ISSUE TITLE
Disable VHost when host does not support vhost-net

### ISSUE THREAD

**Issue by sameo** [containers/virtcontainers#385]
We enable `vhost-net` unconditionally:

https://github.com/containers/virtcontainers/blob/master/qemu.go#L292

We should dynamically toggle it depending on the host `vhost-net` availability.

**Comment by sameo** [comment]
cc @mcastelino

**Comment by egernst** [comment]
I'll take a look and see if this is still relevant...

**Comment by egernst** [comment]
This issue was moved to kata-containers/runtime#169
