### ISSUE TITLE
ci: Test every PR against Clear Containers runtime

### ISSUE THREAD

**Issue by sboeuf** [containers/virtcontainers#408]
Virtcontainers has its own CI with its own tests, but we often end up with some issues when re-vendoring virtcontainers version in clear containers runtime repository. This means that we have to go back and forth between those repos to get the issues fixed. Instead, we should test every PR + master from this repo (virtcontainers) in the runtime environment. That way, we know that we are not breaking Clear Containers every time we push a change to this repo. And that way, no bad surprises when re-vendoring.

**Comment by jodh-intel** [comment]
+1. Of course, if a PR changes the virtcontainers API, this will cause a CI failure but we can deal with those scenarios as they arise.
