### ISSUE TITLE
Networking: Expand the NetworkModel to also describe network properties

### ISSUE THREAD

**Issue by mcastelino** [containers/virtcontainers#412]
Currently the NetworkModel cannot carry along with it any additional data about the desired container network to VM interconnection details. Also this does not allow the runtime to customize the behavior of virtcontainers networking.

```
// NetworkModel describes the type of network specification.
type NetworkModel string

const (
        // NoopNetworkModel is the No-Op network.
        NoopNetworkModel NetworkModel = "noop"

        // CNINetworkModel is the CNI network.
        CNINetworkModel NetworkModel = "CNI"

        // CNMNetworkModel is the CNM network.
        CNMNetworkModel NetworkModel = "CNM"
)
```

By extending the network to a struct we can carry additional information/customization requested by the runtime.
```
type NetworkModel struct {
      PluginModel string
      InterconnectionModel NetInterworkingModel
      ...
}
```

/cc @sameo @sboeuf 

This can be set by the runtime based on the CNI plugin in user (or based on SDN in use) to obtain best performance.

**Comment by sboeuf** [comment]
@mcastelino extending the NetworkModel does not sound like a problem to me. But I would like to understand what kind of network properties we're trying to carry on here ?

**Comment by sameo** [comment]
@sboeuf The VM to container interconnection model, mostly.

@mcastelino This looks really fine to me.

**Comment by egernst** [comment]
AFAICT this was introduced via https://github.com/containers/virtcontainers/pull/393

Please reopen is I am mistaken.
