### ISSUE TITLE
Create a generic type Endpoint

### ISSUE THREAD

**Issue by mcastelino** [containers/virtcontainers#420]
The current ```type Endpoint``` is very specific to the veth-Bridge-tap implementation.

Make this more generic to support all possible interface types including
- veth
- macvlan
- ipvlan
- macvtap
- ipvtap
- vethtap
- vhost-user
- SRIOV (potentially). This is handled by the device abstraction today.

For some context about ipvtap and vethtap

Networking patches to the Linux kernel for VM Native networking

•	VT-x Native Networking Support
	ipvtap support (upstream) - Merged into upstream kernel
	http://lkml.iu.edu/hypermail/linux/kernel/1702.0/04087.html
o	veth-tap support (under review) for merge
	https://www.mail-archive.com/netdev@vger.kernel.org/msg187340.html

•	ipvtap
	Covers gap between container and VM based container networking
•	veth-tap
	Provides direct connection of VM’s to container networks

	Eliminates the need for linux bridge + tap / macvtap to connect VMs to container networks

•	The goal is to use that with 
	https://github.com/containernetworking/cni/pull/420 
•	The implementation of this in CNI (prior to vethtap) has been stalled by limitation in the linux kernel https://patchwork.ozlabs.org/patch/612683/

**Comment by amshinde** [comment]
@mcastelino I am working on an Endpoint abstraction for SRIOV. I have started out with a Physical and Virtual Endpoint.

**Comment by egernst** [comment]
I think this has been addressed via introduction of vhost-user based and SRIOV based interfaces, macvtap support, along with general cleanup.  Please reopen if there is still issue with the definition.
