### ISSUE TITLE
lock: Improve the global locking of virtcontainers

### ISSUE THREAD

**Issue by sboeuf** [containers/virtcontainers#421]
I am gonna try to list what I consider as valid/invalid cases of virtcontainers usage and the appropriate way to handle this through a different locking approach than the very global one we are using right now. Indeed, the global locking is good to easily protect and manage locks between containers, but this is clearly not the most optimized way to do it, and we might have some performance issues related to the bottle necks resulting from this very global approach.

Ok so let's try to list what I consider as valid/invalid usages of virtcontainers:

1. Two calls to `ListPod()` at the same time about 2 different pods/containers (we could imagine a 3rd call asking for the status of a specific pod at the same time).
In that case, we want to read the information, this means we only need a shared/read lock for both of those calls, and specifically we need to add this to the `StatusPod()` function which is called from `ListPod()`.
Now, let's say the subsequent call to `statusContainer()` end up finding a stopped shim, meaning it has to update the status of a container, we will need to switch to an exclusive lock for that. I don't think it's gonna be an issue to release the lock when switching from share to exclusive, and we cannot do differently since this operation is not atomic.
Last thought about this case, we could have the 3rd caller asking for the deletion of a pod (through an exclusive lock), after both `ListPod()` took their shared locks. This means we could have a list of 10 pods from the reading done through `ListPod()`, but really have 9 pods a few seconds later, because of the delete coming after. I don't think this would be an issue since that's the caller's responsibility not to do actions on this deleted pod after it knows it has been deleted, even if `ListPod()` reports something different. Also, I think we already have this potential case right now, and it does not sound like an issue.

2. Several calls to the same pod or container are not allowed since it does not make sense to allow someone to call into `start` or `delete` before `create` for example. And I assume that we have to wait for the return of any command before we can issue a new one, otherwise there is no way to ensure about the integrity of the sequence of actions. According to these explanations, I don't think we need to lock every function of the API based on a PodLock, but instead lock more finely, every time we try to access the storage. This would mean two things, having shared locks when reading the storage through `fetch()` functions, and using exclusive locks when writing through `store()` functions. We have to be careful with the `store()` functions since we would have to fetch again, then update, and finally we could write (all of these being included in the exclusive lock), otherwise we could rely on old data at the moment we would try to store.

3. This 3rd case is more a question than a proposal since I don't know if we should consider this as valid or not. Let's say we have two calls to CreatePod() at the same time for 2 pods with the same ID, we should serialize the creation of pods until we actually store the pod, otherwise we could end up with two identical pods ID, with unknown results there... This is a question since I don't know if we consider this a valid case. I guess it can be valid if we have different orchestrations running on the same host and sharing the same /var/lib/virtcontainers/pods directory.

@grahamwhaley @sameo @jodh-intel let me know what you think about the cases and if you agree about the validity/invalidity of a usage, let me know what you think about the way I plan to solve it !

**Comment by grahamwhaley** [comment]
@sboeuf thanks for putting this down in words!
For (1), I think your logic is correct - that sounded right to me.
For (2) - I think the higher layers (like docker) lock their actions to a single pod/container. I think your logic on locking at the fetch/store level though should work, and be a nicer finer granularity - as long as all the functions are designed with that in mind (like the other mention - lock-read-write-unlock?)
For (3), I'm guessing the second create would fail when it tries to make a pod dir as it would already exist. I don't think having two orchestrators share the same pod space sounds good though.

**Comment by sameo** [comment]
Sorry it took so long...My comments:

> In that case, we want to read the information, this means we only need a shared/read lock for both of those calls, and specifically we need to add this to the StatusPod() function which is called from ListPod().

Correct.

> Now, let's say the subsequent call to statusContainer() end up finding a stopped shim, meaning it has to update the status of a container, we will need to switch to an exclusive lock for that. I don't think it's gonna be an issue to release the lock when switching from share to exclusive, and we cannot do differently since this operation is not atomic.

Dropping a lock from a routine that does not even take it (`statusContainer()` here) is usually not a good sign. And it's potentially racy.
I think it would be much cleaner if we'd offload at least:
```Go
	if !running {
			if err := container.stop(); err != nil {
				return ContainerStatus{}, err
			}
		}
```

to its own go routine where we'd potentially do the container stopping asynchronously. This is where we want to take the write lock.

> This means we could have a list of 10 pods from the reading done through ListPod(), but really have 9 pods a few seconds later, because of the delete coming after.

Yes, that is just fine. The list of pods is only valid when you return it, anything can happen afterwards. btw in that specific case the `delete` would only start once all the read locks are released.

> According to these explanations, I don't think we need to lock every function of the API based on a PodLock, but instead lock more finely, every time we try to access the storage

I would disagree with that. A lock is associated to a piece of data and here we want to lock a pod. We don't want to implement a critical section, or just locking a file. Doing file locking would potentially be racy, we can't assume anything from the layers above us. We must be able to serialize things properly, so the locking should happen at our smallest execution unit, i.e. a pod.
Moreover, locking at the filesystem level would provide a more efficient only for concurrent write/update operations on a single pod implementation. And that's precisely what we're trying to serialize. concurrent read operations should definitely be optimized and that's what you're describing on 1).

> Let's say we have two calls to CreatePod() at the same time for 2 pods with the same ID, we should serialize the creation of pods until we actually store the pod, otherwise we could end up with two identical pods ID, with unknown results there... This is a question since I don't know if we consider this a valid case.

Yes, it's a valid (but should be extremely rare) use case. And once the pod lock is created, one thread should take it exclusively and the other should then fail after it gets the lock and realizes that the container/pod ID already exists.

**Comment by sboeuf** [comment]
We have discussed that offline, and I am okay not trying to go to far on the lock improvement since it could become a nightmare to maintain.
However I have a comment regarding the way to handle this asynchronous goroutine.
We have only one way to handle this because if we lock from the goroutine and the main thread does not wait for the end of it, we don't know if it will have the time to finish and to __really__ update the container. Indeed, the runtime can be called with a `cc-runtime state` call and if we don't wait for this routine, the process could exit pretty quickly. That's why we need some synchronization after `statusContainer()` returns.  

In order to make this work, because this architecture could end up with several calls to container.stop(), we should not return an error when trying to stop an already stopped container. This should be allowed since it could happen and it is not an issue. We would just do nothing in that case.
