### ISSUE TITLE
ci: Improve handling of complex revendoring cases

### ISSUE THREAD

**Issue by sboeuf** [containers/virtcontainers#513]
We have run into an issue yesterday with #494, and there was no way to make the CI pass because of the vendoring complexity. This PR was about adding some code to virtcontainers, but at the same time it was revendoring several packages. The way our CI work in order to test our virtcontainers PRs with the Clear Containers runtime is pretty basic. It copies all the new files to the vendoring inside `runtime/vendor/..../virtcontainers`, but this is not enough in this case. Indeed, the runtime vendoring for the other packages that have been revendored from virtcontainers needs to be updated too.
Because I think that we don't want to handle such complexity with nested layers of vendoring, we should rely mostly on `dep` to do the job.

Therefore, here is the proposal:
- We should have our CI script creating a new branch and pushing to a temporary branch on virtcontainers repo.
- Go to the runtime repository and checkout the right branch/PR(in case we have `Depends-on:` flag)
- Modify the `Gopkg.toml` file to update the constraint revision of virtcontainers as the one corresponding to the virtcontainers branch we've just pushed/created from the CI.
- Run `dep ensure && dep ensure -update github.com/containers/virtcontainers && dep prune`
- Build the runtime from this point, and start our testing as it's usually done.

**Comment by sboeuf** [comment]
cc @sameo @mcastelino

**Comment by mcastelino** [comment]
I am wondering if we created the wrong vendoring strategy to begin with with version locking both repos.

I played around with dep yesterday and noticed an annoying thing
Let us say
- A imports B
- B vendors C version V
- A vendors C version V+1 but A does not actually use C
     - When revendoring in A, dep will vendor in V not V+1

I would have thought it will lock to the higher rev not the lower rev.
I do not know the behavior if A was actually using C.

So one option would be in our CI would be to merge the PR to a branch in virtcontainer and then to revendor from the virtcontainers branch to runtime as @sboeuf was suggesting. However that needs the vendor file in the runtime to be updated, unless we mark the dependencies in A for dependencies of B be not version locked, but just point to master.

That leaves our dependencies like netlink which are used in both A and B. In this case also I think we should set A to point to master and rely on the vendoring lock from B.

cc @sameo @mcastelino @jodh-intel @grahamwhaley

**Comment by sboeuf** [comment]
@mcastelino I think a dependency should not be constrained from the runtime is it is not actually using it. And about a dependency used by runtime and virtcontainers, we should make sure we are not relying on different constraint version, this is our responsibility as maintainers/developers. And in case you are modifying this dependency version from virtcontainers, you have to push a corresponding PR on the runtime so that you can specify `Depends-on:` from virtcontainers. This way we can make sure both repo rely on the same constraints for the test of a specific virtcontainers PR.
