### ISSUE TITLE
Generate an execID for every processes

### ISSUE THREAD

**Issue by sboeuf** [containers/virtcontainers#535]
Virtcontainers should provide an ID to every processes started on every containers. The easy thing is for container's processes, we only need to use the `containerID` as the `execID`, and for the other case, that is `EnterContainer()`, we will generate a new unique ID.
It's important to get this ID generated from the runtime, so that we can provide it both to the shim and the agent. Indeed, the agent will expect such ID to spawn processes on behalf of the runtime, and those IDs have to match the ID from the shim.
This will be pretty straightforward to implement since we already have a `Token` field inside the `Process` structure.

**Comment by egernst** [comment]
This issue was moved to kata-containers/runtime#166
