### ISSUE TITLE
make clean attemps `rm -f /`

### ISSUE THREAD

**Issue by grahamwhaley** [containers/virtcontainers#555]
I did a `make clean`, and it tried to do:

```bash
# make clean
rm -f hack/virtc/virtc
rm -f hook/mock/hook
rm -f /
rm: cannot remove '/': Is a directory
```

Luckily I was just a normal user eh?!!!

The problem looks like we changed from having just `SHIM_DIR` and `SHIM_BIN` to having the `CC_` and `KATA_` prefixed versions.

What is the right thing to do here now - remove both the `CC` and `KATA` path/binaries?

**Comment by grahamwhaley** [comment]
@sboeuf @jodh-intel , if you decide what the right thing to do is I can push a PR... let me know.

**Comment by grahamwhaley** [comment]
Looks like there may be other parts of the `Makefile` that need fixing as well - I see the `uninstall` section for instance still references `SHIM_BIN`

**Comment by jodh-intel** [comment]
Yowzers! Ideally the logic would check that the variables are set and that the directories actually exist (and are not `/` for total parania :)
