### ISSUE TITLE
pod: Wait for VM to be started

### ISSUE THREAD

**Issue by sboeuf** [containers/virtcontainers#565]
Now that we have moved to the model one proxy per VM, we have to make sure the VM is properly started before the proxy tries to connect to its sockets. For this reason, we should ensure the VM is started before we try to start the proxy.

**Comment by egernst** [comment]
Have you seen failures from this, or is this just static analysis?

**Comment by sboeuf** [comment]
This is something we need for Kata proxy. When the `kata-proxy` is going to be started, it won't wait for `register()` to be called, that's why the VM has to be ready in this case.

**Comment by sameo** [comment]
This is fixed with PR #575
