### ISSUE TITLE
ARM: Couldn't find "flags"

### ISSUE THREAD

**Issue by devimc** [containers/virtcontainers#608]
docker: Error response from daemon: OCI runtime create failed: Couldn't find "flags" from "/proc/cpuinfo" output: unknown.

**Comment by grahamwhaley** [comment]
Hmm, for parsing the CPU info to find if a device has the features we need ... - I saw this yesterday, but sadly I suspect this only handles things like vector math extensions, and not VM type stuff.
https://opensource.googleblog.com/2018/02/cpu-features-library.html

**Comment by devimc** [comment]
@grahamwhaley yes, I did't see anything related to virtualization, I think we need to skip that validation in arm

**Comment by sameo** [comment]
@devimc What does `/proc/cpuinfo` look like on this machine?

**Comment by devimc** [comment]
```
processor	: 0
BogoMIPS	: 200.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x43
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0x0a1
CPU revision	: 1

processor	: 1
BogoMIPS	: 200.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x43
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0x0a1
CPU revision	: 1

processor	: 2
BogoMIPS	: 200.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x43
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0x0a1
CPU revision	: 1
```

**Comment by sboeuf** [comment]
What are we supposed to check on x86 with flags ?

**Comment by sameo** [comment]
@sboeuf nesting

@devimc We should simply return `false, nil` if flags are not there.

**Comment by sboeuf** [comment]
Ok then we should throw a warning log. This way, a user on ARM with nesting being not supported, would be able to understand quiclky why it does not work.

**Comment by sameo** [comment]
Yes, a warning should be fine.
