### ISSUE TITLE
Split virtcontainers into smaller packages

### ISSUE THREAD

**Issue by sameo** [containers/virtcontainers#631]
Currently all the virtcontainers code lives under the `virtcontainers` package, making code documentation not clear and all mixed together. See https://godoc.org/github.com/containers/virtcontainers

We should start splitting the code into different logical packages. For example:

- `api` for gathering the https://github.com/containers/virtcontainers/blob/master/documentation/api/1.0/api.md
- `utils` for the externally reachable utilities (things like `RunningOnVMM()` or `SerializeParams()`
- `agent` for adding all agent related structures and interfaces

**Comment by sboeuf** [comment]
This will certainly add some complexity into the code since we won't be able to access everything as easily as we do today, due to the fact that everything is from the same package `main`. Seems like a pretty big change for the purpose of clearer documentation.

**Comment by egernst** [comment]
This issue was moved to kata-containers/runtime#150
