### ISSUE TITLE
[hyperstart] Support the "pod destroyed" event

### ISSUE THREAD

**Issue by dlespiau** [containers/virtcontainers#71]
Currently we don't support "events" from hyperstart. There is one such thing (AFAICS), the destroy pod event that is fired to the CTL channel when the initial workload process finishes.

I've removed that event, for now, from the hyperstart distributed in the clear linux image, but we probably want to support it at some point to work with upstream hyperstart. That may mean big changes for us and the API as we'll need to constantly have a read on the CTL channel and provide a way to forward events to the user of the hyperstart API.

**Comment by sboeuf** [comment]
@sameo, @dlespiau I think we can close this one. We don't have any dependency on this one inside virtcontainers.

**Comment by dlespiau** [comment]
well, we do, no? we don't want the read() on the CTL socket to wait for an ACK and receive an event instead. I think you've fixed this already with the multicasting interface.

**Comment by sboeuf** [comment]
I meant we are not using destroypod with virtcontainers. Let's close this one.

**Comment by dlespiau** [comment]
That's still not a good reason. Even if virtcontainers doesn't issue commands nor consume events directly, it still offers an API to access hyperstart. We have to make sure the hyperstart package can safely receive events and that events don't interfere with sending commands.

That's only for hyperstart 0.8 though, not sure if we'll even go there.
