### ISSUE TITLE
Hyperstart kills a pod when no running containers are left

### ISSUE THREAD

**Issue by sameo** [containers/virtcontainers#83]
When all containers within a pod are done, hyperstart will kill the pod itself. This prevents us from adding a container to a pod if all previously added containers are terminated.

To fix that issue, we need to follow 3 steps:

- [ ] Start a pause container whenever we start a pod. The [pause container](https://github.com/kubernetes-incubator/cri-o/blob/master/pause) will be made of a single binary that sleeps forever.

- [ ] Send a PR to the hyperstart project for optionally keeping pods alive until it receives a kill command.

- [ ] Remove the pause container.

### Pod and pause containers

The pause container will simply be a [single binary](https://github.com/kubernetes-incubator/cri-o/blob/master/pause) that **virtcontainers will statically build**.

When creating a pod through hyperstart, we will:

1) Create a temporary directory containing only the pause static binary
2) Create a pause container which rootfs will point to the pause temporary directory described in 1, in addition to the initial pod containers.
3) Start the pod.

When deleting a pod we will:

1) Kill all containers, including the pause containers
2) Destroy the pod
3) Remove the pause temporary directory

### Notes

- We may want to share the same pause rootfs across all hyperstart created pods.
- The current pod rootfs field should be removed, it does not make sense.

**Comment by laijs** [comment]
we might need to change the hyperstart for it,
hyperstart could be changed to avoid to kill the pod when all containers exit.
what do you think?

**Comment by sboeuf** [comment]
@laijs that's the plan explained in this issue. We first want to fix it locally with a temporary solution (look at PR #80) and then submit a PR to hyperstart to prevent the pod from being killed when no containers are remaining.

**Comment by sameo** [comment]
@laijs we were planning to send a PR for that, it would be definitely useful. For both virtcontainers and Clear Containers.

**Comment by gnawux** [comment]
@laijs @sameo  IIRC, the current hyperstart master won't exit pod when all containers exit. The latest hyperd allows an empty running pod without container in it.

With https://github.com/hyperhq/hyperd/pull/469, we could

- create empty pod
- add and run container inside the pod
- stop containers inside the pod
- remove all containers from the pod

and leave a running empty pod. The hyperstart won't exit.

**Comment by sboeuf** [comment]
@gnawux I am not sure about what does the latest hyperstart but I can tell you that we can already start an empty pod if we create a pod without any container. The remaining issue we have is when we start a workload (aka a container with commands), once this workload execution is done, the pod exit because there is nothing left running on the pod.

**Comment by gnawux** [comment]
@sboeuf What's the hyperstart version you are working on? I believe I can quit the last container and leave an empty pod running with recent version of hyperstart.

**Comment by gnawux** [comment]
The latest hyperd could do this:

```
➜ sudo ./hyperctl list container
Container ID                                                       Name                 POD ID              Status
a8fd34f686e6587979936df880b9e9144fefd895d19560493d2028aa82c47f0c   busybox-2602968228   nginx-8530075287    running
6e8c08420389a165682586380fa35432f5922287b9aec34059ed1ff68b3f1623   nginx-8530075287     nginx-8530075287    running
➜ sudo ./hyperctl stop -c busybox-2602968228 nginx-8530075287
➜ sudo ./hyperctl list container
Container ID                                                       Name                 POD ID              Status
6e8c08420389a165682586380fa35432f5922287b9aec34059ed1ff68b3f1623   nginx-8530075287     nginx-8530075287    succeeded
a8fd34f686e6587979936df880b9e9144fefd895d19560493d2028aa82c47f0c   busybox-2602968228   nginx-8530075287    succeeded
➜ sudo ./hyperctl rm -c busybox-2602968228 nginx-8530075287
container busybox-2602968228 is successfully deleted!
container nginx-8530075287 is successfully deleted!
➜ sudo ./hyperctl list container
Container ID        Name                POD ID              Status
➜ sudo ./hyperctl list
POD ID              POD Name            VM name             Status
nginx-8530075287    nginx-8530075287    vm-pqEnBvQVdS       running
```

**Comment by sboeuf** [comment]
@gnawux that is a good news, I will check on my side and I will confirm if it solves the issue for me.

**Comment by gnawux** [comment]
@sboeuf discussed with hyperstart team, and my colleague think there is still a minor issue if we want to re-launch a container in the empty running pod, but he could fix this easily.

**Comment by sboeuf** [comment]
@gnawux that's a good news, let me know when the fix should land in the master branch.
BTW, I am testing with latest hyperstart and I get CMD 23 (PROCESSASYNCEVENT) instead of getting CMD 9 (ACK) when I try to stop the pod (sending REMOVECONTAINER). Do you know what does that mean ?

**Comment by wcwxyz** [comment]
@sboeuf It seems like hyperstart will no longer send process exit code via IO channel (followed after EOF). Instead PROCESSASYNCEVENT is sent via control channel. Exit code is in its payload.

Check this out: https://github.com/hyperhq/hyperstart/pull/235/commits/ecfb7e9ba33a91d89b465776d62b3c7a61d05f68

**Comment by sboeuf** [comment]
@wcwxyz Ohhh this is a big change... What is the role of IO channel now ?

**Comment by gnawux** [comment]
@sboeuf The PR https://github.com/hyperhq/hyperstart/pull/251 has been merged. 

And on `PROCESSASYNCEVENT`, the aim is to make all control message in the control channel, including the exit code of processes. I think @laijs have more detail of it.

I think we'd better have a discuss group or mailing list on hyperstart changes, as it is not only used by runV now.

**Comment by sboeuf** [comment]
@gnawux I confirm the latest version (including PR#251) fixes the issue related to pod and containers being killed when no workload running. We will be able to remove the pause container from virtcontainers.

**Comment by sboeuf** [comment]
The pause container that we have introduced fixes this issue.
