### ISSUE TITLE
"/usr/local/var/run/cc-oci-runtime/proxy.sock" is a bad default path

### ISSUE THREAD

**Issue by dlespiau** [containers/virtcontainers#90]
/var/run/cc-oci-runtime/proxy.sock should probably be the default path, there's no way non-development setups will end up in /usr/local.

Of course, an even better option would be to be able to specify this path when creating the proxy object.

Which reminds me, we may want to rename that path to /var/run/clear-containers or /var/run/clearcontainers.

**Comment by sboeuf** [comment]
This is merged already.
